import "./globals.css";
import { Roboto } from "next/font/google";
import { Metadata } from "next";

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  variable: "--font--roboto",
});

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "beeceptor",
    template: "%s | beeceptor",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto_init.variable}`}>{children}</body>
    </html>
  );
}
